nothig here yet

In [11]:
import torch

t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0,-4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = [x*0.1 for x in t_c]
t_u = [x*0.1 for x in t_u]
t_c = torch.tensor(t_c).unsqueeze(1)
t_u = torch.tensor(t_u).unsqueeze(1)

t_u.shape

torch.Size([11, 1])

making a model using torch nn

In [12]:
"""
this this linear model so it will only have one linear layer
followed by an optimization function
which will take care of the calculating the derivative/gradient
and updating the paremeters

the optimizer we are using is stochastic gradient decent
"""

import torch.nn as nn
import torch.optim as optim

linear_model = nn.Linear(1,1)
optimizer = optim.SGD(
    lr=1e-2,
    params=linear_model.parameters(),
)

list(linear_model.parameters())

[Parameter containing:
 tensor([[-0.5713]], requires_grad=True),
 Parameter containing:
 tensor([0.7955], requires_grad=True)]

creating a training loop with nn linear model

In [13]:
def training_loop(
        n_epochs,
        optimizer,
        model,
        loss_fn,
        t_c,
        t_u
    ):

    for epoch in range(1,n_epochs+1):
        t_p = model(t_u)
        loss = loss_fn(t_p, t_c)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch == 1 or epoch % 1000 == 0:
            print(f"Epoch {epoch}, Training loss {loss.item():.4f},")



In [14]:
training_loop(
    n_epochs=3000,
    model=linear_model,
    optimizer=optimizer,
    loss_fn= nn.MSELoss(),
    t_u=t_u,
    t_c=t_c
)
print()
print(linear_model.weight)
print(linear_model.bias)

Epoch 1, Training loss 13.5201,
Epoch 1000, Training loss 0.0497,
Epoch 2000, Training loss 0.0300,
Epoch 3000, Training loss 0.0293,

Parameter containing:
tensor([[0.5339]], requires_grad=True)
Parameter containing:
tensor([-1.7144], requires_grad=True)


now with a sequential model